<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Cool GitHub Page</title>
    <link rel="stylesheet" href="styles.css">
    <script src="script.js" defer></script>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav>
            <h1>My Portfolio</h1>
            <ul>
                <li><a href="#about">About</a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <div class="hero">
        <h1>Welcome to My GitHub Page</h1>
        <p>Awesome design with parallax effect</p>
        <a href="#about" class="btn">Explore More</a>
    </div>

    <section id="about">
        <h2>About Me</h2>
        <p>I'm a passionate developer who loves creating awesome web experiences.</p>
    </section>

    <section id="projects">
        <h2>My Projects</h2>
        <div class="project-grid">
            <div class="project">
                <h3>Project One</h3>
                <p>A cool project description goes here.</p>
            </div>
            <div class="project">
                <h3>Project Two</h3>
                <p>Another cool project description goes here.</p>
            </div>
        </div>
    </section>

    <section id="contact">
        <h2>Contact Me</h2>
        <p>Let's collaborate! Reach out to me via social media.</p>
        <div class="social-icons">
            <a href="https://github.com/yourusername" target="_blank"><i class="fab fa-github"></i></a>
            <a href="https://twitter.com/yourusername" target="_blank"><i class="fab fa-twitter"></i></a>
            <a href="mailto:yourname@email.com"><i class="fas fa-envelope"></i></a>
        </div>
    </section>

    <footer>
        <p>Made with ❤️ by <a href="https://github.com/yourusername" target="_blank">Your Name</a></p>
    </footer>
</body>
</html>

